version: '3.3'
services:
  db:
    container_name: sql-anti-patterns
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3314:3306"
    volumes:
      - "./docker/mysql/initdb.d:/docker-entrypoint-initdb.d"
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/log:/var/log/mysql"